### ISSUE TITLE
migrate to new templates

### ISSUE THREAD

**Issue by evanwill** [uidaholib/digital-collections-template-cb-csv#10]
migrate these branches into the new templates following the current conventions:

- [x]  bhrle
- [x]  cnr
- [x]  genesee-news
- [x]  hohp
- [x]  lrcdp
- [x]  otherfaces
- [x]  rwhp
- [x]  sanborn
- [x]  taylorarchive

Tasks: 

- Update metadata to use new object location (from "/digital/objects/" to "objects.lib.uidaho.edu"
- ensure follows conventions stub, branch, metadata all named in same way

**Comment by aweymo-ui** [comment]
The "taylorarchive" looks like an incomplete collection but I migrated "twrs" which is connected to "taylorarchive" on the digital-collections-template-cb-csv
