### ISSUE TITLE
stop-words not recognized in _includes/index/featured-terms.html

### ISSUE THREAD

**Issue by juliastone0729** [uidaholib/digital-collections-template-cb-csv#4]
The subjects-stopwords configured in the theme.yml file are not tied to the 'Top Subjects' featured on the homepage via the featured-terms include. Trying to find a way to apply the stopwords 'natural resources' and 'forestry' (see screenshot):

<img width="373" alt="Screenshot 2023-08-24 at 12 35 27 PM" src="https://github.com/uidaholib/digital-collections-template-cb-csv/assets/123985223/438c058b-3c51-44f8-bf48-65897d55deda">

**Comment by evanwill** [comment]
@juliastone0729  there is no stopwords option for the "index/featured-terms.html" include (it is too complicated to implement in Liquid!). In this sort of case I would usually:

- first, increase the "max" option in the include to look at the common terms or look at the subject cloud
- then based on that, manually create a list of terms that make sense to feature
- then add the list as the "featured" option of the include (and remove the "field" option)

This won't auto change if the metadata is updated, but can offer more sensible customization of terms you actually want to highlight.

**Comment by evanwill** [comment]
For example, your include might look like:

```
{% include index/featured-terms.html featured="natural resource occupations;students;professors" title="Top Subjects" btn-color="primary" %}
```
