### ISSUE TITLE
Issue with video includes -- unlisted YT videos

### ISSUE THREAD

**Issue by juliastone0729** [uidaholib/digital-collections-template-cb-csv#5]
Video includes are not properly showing up -- I’m not sure if maybe YouTube changed things so that unlisted videos cannot be included/embedded anymore? (**Public YouTube videos are still working properly, just not unlisted ones**)
 
I tried the following includes but they both showed that the video is unavailable:

`{% include feature/video.html objectid="https://www.youtube.com/watch?v=nrho0JmUxzA" width="75" caption="A 1992 promotional video about the College of Forestry, Wildlife and Range Sciences" %}`
 
`{% include feature/video.html objectid="cnr063" width="75" caption="A 1992 promotional video about the College of Forestry, Wildlife and Range Sciences" %}`

<img width="885" alt="Screenshot 2023-08-24 at 11 19 43 AM" src="https://github.com/uidaholib/digital-collections-template-cb-csv/assets/123985223/1e050a22-b1ff-42a9-b91e-456bc7d74070">

**Comment by evanwill** [comment]
@juliastone0729 ,  @dcnb emailed about the issue--> the unlisted vids will work when on live web, but don't work on your dev server. It will be fine once we deploy to the final location!
