### ISSUE TITLE
genesee-news replace featured image

### ISSUE THREAD

**Issue by evanwill** [uidaholib/digital-collections-template-cb-csv#9]
Current featured image is a CONTENTdm link. 
Download the current image and place a copy in the genesee collection's objects folder on the server, then update featured image link. 

Current image: https://digital.lib.uidaho.edu/digital/iiif/cities/929/full/max/0/default.jpg

future image will be something like https://www.lib.uidaho.edu/digital/objects/genesee-news/cities929.jpg

**Comment by aweymo-ui** [comment]
I added this new image, updated the link in the theme and rake deployed again. That said, I am still seeing the old link when I am inspecting the page source. This is likely a caching problem -- but let me know if I missed a step in the process here.

**Comment by aweymo-ui** [comment]
Updated the _site assets on the Web Drive and the link is updated in the page source.
